// Shared feed/niche configuration — used by digest, trends, and notifications routes.
// Extracted from server.js so it has one home instead of being duplicated.
const RSSParser = require("rss-parser");
const parser = new RSSParser({ timeout: 8000, headers: { "User-Agent": "Mozilla/5.0 CreatorPulseBot/1.0" } });

const NICHE_QUERIES = {
  "Football/Soccer": "football soccer premier league champions league transfer",
  "Basketball": "NBA basketball Lakers Warriors",
  "Tennis": "tennis Wimbledon Grand Slam ATP WTA",
  "Cricket": "cricket IPL Test match World Cup",
  "Formula 1": "Formula 1 F1 Grand Prix McLaren Ferrari",
  "Boxing": "boxing fight heavyweight champion",
  "MMA/UFC": "UFC MMA fight octagon",
  "WWE Wrestling": "WWE wrestling Raw SmackDown",
  "American Football": "NFL American football touchdown Super Bowl",
  "Baseball": "MLB baseball World Series",
  "Ice Hockey": "NHL hockey Stanley Cup",
  "Golf": "golf PGA Tour Masters",
  "Rugby": "rugby Six Nations World Cup",
  "Athletics/Track": "athletics track field Olympics sprint",
  "Cycling": "cycling Tour de France Giro",
  "Swimming": "swimming Olympics world record",
  "Esports": "esports gaming tournament League of Legends",
  "Volleyball": "volleyball Olympics championship",
  "Celebrity Gossip": "celebrity gossip Hollywood entertainment",
  "Music (Afrobeats)": "Afrobeats Burna Boy Wizkid Davido music",
  "Music (Hip-Hop)": "hip hop rap Drake Kendrick music album",
  "Music (Pop)": "pop music Taylor Swift chart album",
  "Music (R&B)": "R&B soul music Beyonce album",
  "Music (K-Pop)": "K-pop BTS BLACKPINK Korean music",
  "Music (Amapiano)": "Amapiano South Africa music",
  "Movies & TV": "movies TV series Netflix box office",
  "Anime": "anime manga One Piece Naruto release",
  "Korean Drama": "Korean drama K-drama Netflix series",
  "Bollywood": "Bollywood India movies film box office",
  "Pop Culture": "pop culture viral trending internet",
  "Console Gaming": "PlayStation Xbox Nintendo gaming console",
  "PC Gaming": "PC gaming Steam graphics card GPU",
  "Mobile Gaming": "mobile gaming iOS Android game",
  "Game Reviews": "video game review launch release",
  "Twitch Streaming": "Twitch streaming streamer live",
  "YouTube Gaming": "YouTube gaming channel video",
  "Travel": "travel destination vacation tourism",
  "Food & Recipes": "food recipe cooking chef restaurant",
  "Fitness & Gym": "fitness gym workout health exercise",
  "Mental Health": "mental health wellness therapy anxiety",
  "Relationships & Dating": "relationships dating love advice",
  "Parenting": "parenting children family baby",
  "Minimalism": "minimalism lifestyle simple living",
  "Home Decor": "home decor interior design renovation",
  "Pets": "pets dogs cats animals viral",
  "Streetwear": "streetwear sneakers Supreme Nike Jordan hypebeast",
  "Luxury Fashion": "luxury fashion Gucci Louis Vuitton Chanel runway",
  "Skincare": "skincare beauty routine dermatology",
  "Makeup": "makeup beauty cosmetics tutorial",
  "Haircare": "haircare natural hair styling products",
  "Personal Finance": "personal finance money saving investing",
  "Crypto": "cryptocurrency Bitcoin Ethereum crypto price",
  "Stock Market": "stock market Wall Street S&P 500 trading",
  "Side Hustles": "side hustle passive income make money online",
  "Business News": "business startup entrepreneur funding",
  "Real Estate Investing": "real estate property investment market",
  "Budgeting": "budgeting money management finance tips",
  "AI & Tech News": "artificial intelligence AI OpenAI tech startup",
  "Gadget Reviews": "gadget tech review iPhone Samsung",
  "Coding & Dev Life": "programming coding developer software",
  "Startups": "startup funding venture capital tech",
  "Cybersecurity": "cybersecurity hack data breach privacy",
  "Space & Science": "space NASA SpaceX science discovery",
  "Science": "science discovery research breakthrough",
  "History": "history ancient civilization discovery",
  "Language Learning": "language learning Spanish French Duolingo",
  "Productivity": "productivity habits time-blocking focus deep work",
  "Study Tips": "study tips learning education student",
  "Philosophy": "philosophy life meaning ethics",
  "Psychology": "psychology behavior mind mental",
  "Yapping Videos": "viral controversial opinion debate",
  "Hot Takes": "hot take controversial opinion debate",
  "Rants": "rant viral opinion social media",
  "Storytelling": "storytelling viral story true crime",
  "Political Commentary": "politics government policy news",
  "True Crime": "true crime murder mystery investigation",
  "Mystery & Unexplained": "mystery unexplained paranormal conspiracy",
  "Viral Dances": "TikTok dance trend viral challenge",
  "Trend Reaction": "TikTok viral trend reaction internet",
  "Challenge Content": "TikTok viral challenge trend",
  "YouTube Growth": "YouTube growth subscribers views monetization",
  "Social Media Tips": "social media marketing tips growth",
  "Brand Deals": "brand deals sponsorship influencer marketing",
  "Monetization Advice": "monetization content creator income",
  "Medicine & Health": "health medicine doctor treatment news",
  "Law": "law legal court ruling news",
  "Marketing": "marketing digital advertising brand",
  "Entrepreneurship": "entrepreneurship business success startup",
  "Motivational Speaking": "motivation success mindset inspiration",
  "Faith & Religion": "faith religion church spirituality",
  "African Culture": "African culture Nigeria Ghana music art",
  "Caribbean Culture": "Caribbean culture Jamaica Trinidad music",
  "Astrology": "astrology zodiac horoscope Mercury retrograde",
  "Self-Development": "self development personal growth mindset"
};

// Expanded RSS lists per niche. Google News RSS acts as a catch-all query.
function googleNews(q) { return `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`; }

const NICHE_RSS = {
  "Football/Soccer": "https://feeds.bbci.co.uk/sport/football/rss.xml",
  "Basketball": "https://feeds.bbci.co.uk/sport/basketball/rss.xml",
  "Music (Afrobeats)": googleNews("Afrobeats"),
  "Crypto": "https://cointelegraph.com/rss",
  "AI & Tech News": "https://feeds.feedburner.com/TechCrunch",
  "Movies & TV": "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
  "default": "https://feeds.bbci.co.uk/news/rss.xml"
};

const NICHE_BLOG_RSS = {
  "Football/Soccer": ["https://www.goal.com/rss/en/news","https://www.skysports.com/rss/0,,12040,00.xml","https://www.espn.com/espn/rss/football/news","https://www.theguardian.com/football/rss","https://www.90min.com/posts.rss"],
  "Basketball": ["https://www.espn.com/espn/rss/basketball/news","https://bleacherreport.com/articles/feed","https://www.si.com/nba/rss","https://www.cbssports.com/nba/rss"],
  "American Football": ["https://www.espn.com/espn/rss/nfl/news","https://profootballtalk.nbcsports.com/feed/","https://www.cbssports.com/nfl/rss"],
  "Formula 1": ["https://www.autosport.com/rss/feed/f1","https://www.motorsport.com/rss/f1/news","https://www.formula1.com/en/latest/all.xml"],
  "Boxing": ["https://www.boxingscene.com/rss.xml","https://www.badlefthook.com/rss/current.xml"],
  "MMA/UFC": ["https://www.mmafighting.com/rss/current.xml","https://www.bloodyelbow.com/rss/current.xml"],
  "Tennis": ["https://www.tennis.com/rss","https://www.atptour.com/en/media/rss-feed/xml-feed"],
  "Cricket": ["https://www.espncricinfo.com/rss/content/story/feeds/0.xml"],
  "Golf": ["https://www.pgatour.com/content/pgatour/rss.rss.pga.rss"],
  "Ice Hockey": ["https://www.espn.com/espn/rss/nhl/news"],
  "Baseball": ["https://www.espn.com/espn/rss/mlb/news"],
  "Rugby": ["https://www.rugbyworld.com/feed"],
  "Esports": ["https://www.dotesports.com/feed","https://dbltap.com/rss.xml"],
  "Crypto": ["https://cointelegraph.com/rss","https://cryptobriefing.com/feed","https://www.coindesk.com/arc/outboundfeeds/rss/","https://decrypt.co/feed"],
  "Stock Market": ["https://www.cnbc.com/id/10001147/device/rss/rss.html","https://feeds.marketwatch.com/marketwatch/topstories/"],
  "AI & Tech News": ["https://feeds.feedburner.com/TechCrunch","https://www.theverge.com/rss/index.xml","https://www.wired.com/feed/rss","https://venturebeat.com/feed"],
  "Gadget Reviews": ["https://www.engadget.com/rss.xml","https://www.theverge.com/rss/index.xml"],
  "Cybersecurity": ["https://feeds.feedburner.com/TheHackersNews","https://krebsonsecurity.com/feed/"],
  "Startups": ["https://feeds.feedburner.com/TechCrunch","https://www.ycombinator.com/blog/rss"],
  "Space & Science": ["https://www.nasa.gov/rss/dyn/breaking_news.rss","https://www.space.com/feeds/all"],
  "Movies & TV": ["https://www.hollywoodreporter.com/feed","https://variety.com/feed","https://deadline.com/feed"],
  "Anime": ["https://www.animenewsnetwork.com/all/rss.xml"],
  "Music (Hip-Hop)": ["https://hiphopdx.com/feed","https://www.xxlmag.com/feed"],
  "Music (Pop)": ["https://www.billboard.com/feed/"],
  "Music (Afrobeats)": [googleNews("Afrobeats OR Burna Boy OR Wizkid OR Davido"), googleNews("Rema OR Tems OR Asake")],
  "Music (K-Pop)": ["https://www.soompi.com/feed","https://www.allkpop.com/feed"],
  "Celebrity Gossip": ["https://www.tmz.com/rss.xml"],
  "Fitness & Gym": ["https://www.menshealth.com/rss/all.xml/","https://www.womenshealthmag.com/rss/all.xml/"],
  "Food & Recipes": ["https://www.bonappetit.com/feed/rss","https://www.food52.com/blog.rss"],
  "Travel": ["https://www.cntraveler.com/feed/rss","https://www.travelandleisure.com/feed"],
  "Streetwear": ["https://hypebeast.com/feed"],
  "Luxury Fashion": ["https://www.vogue.com/feed/rss","https://www.gq.com/feed/rss"],
  "True Crime": [googleNews("true crime murder investigation")],
  "Political Commentary": ["https://www.politico.com/rss/politicopicks.xml"],
  "Business News": ["https://feeds.bloomberg.com/markets/news.rss","https://www.reuters.com/rssfeed/businessNews"],
  "default": ["https://feeds.bbci.co.uk/news/rss.xml"]
};

module.exports = { parser, googleNews, NICHE_QUERIES, NICHE_RSS, NICHE_BLOG_RSS };
  
